# language: php
build:
  nodes:
    tests: true
    analysis:
      dependencies:
        after:
          # The following installs the most recent XOOPS CMS version, you might want
          # to install a specific release tag or branch instead.
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
filter:
  excluded_paths:
    - "class/Export/"
  dependency_paths:
    - XoopsModules25x/*
    - wgsimpleacc/*
